defaults:
  - /robot@_global_.robot: g1_dof27
  - high_jump
  - _self_

dataset:
  folder: ${base}/resources/dataset/g1_dof27_data/high_jump/output
  joint_mapping: ${base}/resources/dataset/g1_dof27_data/joint_id.txt
