
defaults:
  - /robot@_global_.robot: g1_dof27
  - tennis_hit
  - _self_

dataset:
  folder: ${base}/resources/dataset/g1_dof27_data/tennis_hit/output
  joint_mapping: ${base}/resources/dataset/g1_dof27_data/joint_id.txt
