defaults:
  - /dataset/g1_dof29/standard_box_carry_fixed@_here_
  - _self_
task_id: standard_box_carry_carry_distance
box_carry_task:
  box_distance_range: [0.42, 0.42]
  carry_distance_range: [0.20, 0.50]
